# Neural Network Implementation 

In [0]:
import pandas as pd
import numpy as np
import keras as ks 

np.random.seed(5)




**Importing DataSet**

In [0]:
data=pd.read_csv('drive/My Drive/app/creditcard.csv')

In [8]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

**Normalizing Amount **

In [48]:
from sklearn.preprocessing import StandardScaler
data['normalizedamt']=StandardScaler().fit_transform(data['Amount'].values.reshape(-1,1))
data = data.drop(['Amount'],axis=1)
data = data.drop(['Time'],axis=1)
data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10      ...             V21       V22       V23  \
0  0.098698  0.363787  0.090794      ...       -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974      ...       -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643      ...        0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952      ...       -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074      ...       -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Class  normalizedamt  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053      0       0.244964  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724      0      -0.342475  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752      0       1.160686  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458      0       0.140534  
4  0.141267 -0.206010  0.502292  0.219422  0.215153      0      -0.073403  

[5 rows x 30 columns]

In [0]:
X = data.iloc[:, data.columns != 'Class']
y = data.iloc[:, data.columns == 'Class']

**DataSplit**

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=5)
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

**Creating Model **

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
model = Sequential([
    Dense(units=18, input_dim = 29,activation='relu'),
    Dense(units=26,activation='relu'),
    Dropout(0.5),
    Dense(22,activation='relu'),
    Dense(22,activation='relu'),
    Dense(1,activation='sigmoid'),
])

In [52]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 18)                540       
_________________________________________________________________
dense_7 (Dense)              (None, 26)                494       
_________________________________________________________________
dropout_2 (Dropout)          (None, 26)                0         
_________________________________________________________________
dense_8 (Dense)              (None, 22)                594       
_________________________________________________________________
dense_9 (Dense)              (None, 22)                506       
_________________________________________________________________
dense_10 (Dense)             (None, 1)                 23        
Total params: 2,157
Trainable params: 2,157
Non-trainable params: 0
_________________________________________________________________


In [53]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=10,epochs=10)

Epoch 1/10
213605/213605 [==============================] - 29s 138us/step - loss: 0.0113 - acc: 0.9988
Epoch 2/10
213605/213605 [==============================] - 29s 138us/step - loss: 0.0054 - acc: 0.9993
Epoch 3/10
213605/213605 [==============================] - 29s 136us/step - loss: 0.0048 - acc: 0.9993
Epoch 4/10
213605/213605 [==============================] - 29s 136us/step - loss: 0.0042 - acc: 0.9994
Epoch 5/10
213605/213605 [==============================] - 29s 135us/step - loss: 0.0044 - acc: 0.9994
Epoch 6/10
213605/213605 [==============================] - 29s 136us/step - loss: 0.0042 - acc: 0.9994
Epoch 7/10
213605/213605 [==============================] - 29s 137us/step - loss: 0.0041 - acc: 0.9993
Epoch 8/10
213605/213605 [==============================] - 29s 134us/step - loss: 0.0040 - acc: 0.9994
Epoch 9/10
213605/213605 [==============================] - 29s 135us/step - loss: 0.0042 - acc: 0.9994
Epoch 10/10
213605/213605 [==============================] - 28s

In [54]:
score = model.evaluate(X_test, y_test)

71202/71202 [==============================] - 1s 21us/step


In [56]:
print(score)

[0.00454572668325796, 0.9994241734782731]


**Prediction on Test Set**

In [0]:

from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
cnf_matrix = confusion_matrix(y_test, y_pred.round())

In [58]:
print(cnf_matrix)

[[71062    19]
 [   22    99]]


**Prediction on Complete DataSet**

In [59]:
y_pred = model.predict(X)
cnf_matrix = confusion_matrix(y, y_pred.round())
print(cnf_matrix)

[[284240     75]
 [    86    406]]


# **Deep Learning  with SMOTE**

In [0]:
from imblearn.over_sampling import SMOTE

In [61]:
X_resample, y_resample = SMOTE().fit_sample(X,y.values.ravel())
y_resample = pd.DataFrame(y_resample)
X_resample = pd.DataFrame(X_resample)
X_train, X_test, y_train, y_test = train_test_split(X_resample,y_resample,test_size=0.25)
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,y_train,batch_size=10,epochs=10)

Epoch 1/10
426472/426472 [==============================] - 59s 138us/step - loss: 0.0337 - acc: 0.9893
Epoch 2/10
426472/426472 [==============================] - 59s 137us/step - loss: 0.0122 - acc: 0.9970
Epoch 3/10
426472/426472 [==============================] - 61s 142us/step - loss: 0.0101 - acc: 0.9977
Epoch 4/10
426472/426472 [==============================] - 59s 138us/step - loss: 0.0092 - acc: 0.9980
Epoch 5/10
426472/426472 [==============================] - 59s 138us/step - loss: 0.0082 - acc: 0.9982
Epoch 6/10
426472/426472 [==============================] - 58s 137us/step - loss: 0.0075 - acc: 0.9984
Epoch 7/10
426472/426472 [==============================] - 59s 138us/step - loss: 0.0071 - acc: 0.9984
Epoch 8/10
426472/426472 [==============================] - 63s 148us/step - loss: 0.0073 - acc: 0.9985
Epoch 9/10
426472/426472 [==============================] - 60s 140us/step - loss: 0.0074 - acc: 0.9985
Epoch 10/10
426472/426472 [==============================] - 59s

In [63]:
score = model.evaluate(X_test, y_test)
print(score)

142158/142158 [==============================] - 3s 21us/step
[0.005935482583539953, 0.9986704933946735]


**Prediction for Test Set**

In [0]:

y_pred = model.predict(X_test)
y_expected = pd.DataFrame(y_test)
cnf_matrix = confusion_matrix(y_expected, y_pred.round())

In [68]:
print(cnf_matrix)

[[70919   152]
 [   37 71050]]


**Prediction For Whole Data Set **

In [69]:
y_pred = model.predict(X)
cnf_matrix = confusion_matrix(y, y_pred.round())
print(cnf_matrix)

[[283763    552]
 [     4    488]]
